// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndqajnofifdbqmpaqtjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kcWFqbm9maWZkYnFtcGFxdGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzM0MDksImV4cCI6MjA3MzUwOTQwOX0.F7R5iLxbex24q_skiYCOm6YN-oQkU7Crpod-OC2oCtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});